<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9523d97132b7ed07afb0df6fd57b4f16
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9523d97132b7ed07afb0df6fd57b4f16::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9523d97132b7ed07afb0df6fd57b4f16::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9523d97132b7ed07afb0df6fd57b4f16::$classMap;

        }, null, ClassLoader::class);
    }
}
